-- Append handoff pipeline instructions to the orchestrator system prompt
UPDATE public.agent_definitions
SET system_prompt = system_prompt || E'\n\n## Agent Handoff Pipelines\n\nWhen a task requires multiple agents in sequence (e.g. design then build, research then outreach),\nuse the next_agent and next_instruction parameters in delegate_task to chain them together.\nThe first agent''s output is automatically passed as context to the next agent.\n\nExample: delegate to designer with next_agent="engineering" and\nnext_instruction="Build the app based on this design: {RESULT}"\n\nYou can chain any number of agents. Each handoff task appears as a normal pending task\nin the pipeline so the CEO can see and intervene at any step.\n\nUse handoffs when:\n- Work naturally flows between specialties (design → engineering, research → growth)\n- The output of one agent is a direct input for the next\n- You want to set up an autonomous multi-step workflow\n\nDo NOT use handoffs when:\n- You need to review intermediate results before the next step\n- The steps are independent and can run in parallel (just delegate separately)',
    updated_at = now()
WHERE slug = 'orchestrator';

-- Also update the base template
UPDATE public.base_agent_definitions
SET system_prompt = system_prompt || E'\n\n## Agent Handoff Pipelines\n\nWhen a task requires multiple agents in sequence (e.g. design then build, research then outreach),\nuse the next_agent and next_instruction parameters in delegate_task to chain them together.\nThe first agent''s output is automatically passed as context to the next agent.\n\nExample: delegate to designer with next_agent="engineering" and\nnext_instruction="Build the app based on this design: {RESULT}"\n\nYou can chain any number of agents. Each handoff task appears as a normal pending task\nin the pipeline so the CEO can see and intervene at any step.\n\nUse handoffs when:\n- Work naturally flows between specialties (design → engineering, research → growth)\n- The output of one agent is a direct input for the next\n- You want to set up an autonomous multi-step workflow\n\nDo NOT use handoffs when:\n- You need to review intermediate results before the next step\n- The steps are independent and can run in parallel (just delegate separately)'
WHERE slug = 'orchestrator';
